package metadata

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGenerateFileHash(t *testing.T) {
	// Create a temporary test file in a temporary directory
	dir := t.TempDir()
	filePath := filepath.Join(dir, "sample.txt")
	content := []byte("this is a test file for hashing")

	if err := os.WriteFile(filePath, content, 0644); err != nil {
		t.Fatalf("Failed to create test file: %v", err)
	}

	// The expected SHA-256 hash for the content "this is a test file for hashing"
	// This hash was generated by the test itself, to ensure consistency.
	expectedHash := "ceaae15918e3236851a8b85efa977eda4e5bae5fa9d09ee48ec973993f229d1c"

	hash, err := generateFileHash(filePath)
	if err != nil {
		t.Fatalf("generateFileHash() returned an unexpected error: %v", err)
	}

	if hash != expectedHash {
		t.Errorf("generateFileHash() hash mismatch: got %q, want %q", hash, expectedHash)
	}
}
