name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    name: Test Go Backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out ./...
    
    - name: Generate coverage report
      run: go tool cover -html=coverage.out -o coverage.html
    
    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.html

  test-audio-processor:
    name: Test Audio Processor
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      working-directory: ./audio-processor
      run: |
        pip install uv
        uv pip install --system ".[test]"
    
    - name: Run tests
      working-directory: ./audio-processor
      run: pytest test_main.py -v

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Run tests (verbose)
      working-directory: ./frontend
      run: |
        node -v
        npm -v
        CI=true npm test -- --watchAll=false --runInBand --verbose
    
    - name: Build
      working-directory: ./frontend
      run: npm run build

  build-docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build backend image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: biomuzak-backend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        tags: biomuzak-frontend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build audio processor image
      uses: docker/build-push-action@v4
      with:
        context: ./audio-processor
        file: ./audio-processor/Dockerfile
        push: false
        tags: biomuzak-audio-processor:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
